export const ADD_ITEM_IN_CART = "ADD_ITEM_IN_CART";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
export const UPDATE_QUANTITY_CART_ITEM = "UPDATE_QUANTITY_CART_ITEM";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_ROLE = "UPDATE_ROLE";
export const CHANGE_MODE = "CHANGE_MODE";